// Generated by CoffeeScript 1.8.0
(function() {
  console.clear();

  $(document).ready(function() {
    console.log("doc reaady");
    return $('#btnSubmit').click(function() {
      var v;
      console.log("clicky!!!");
      $('#btnSubmit').disabled = true;
      v = $('#emailAddress')[0].value;
      $('#emailResponse').html('<img src="ajax-loader.gif" border="0" />').css('backgroundColor', 'ffffd0');
      return $.getJSON('php/notify.php', {
        email: v
      }, function(d) {
        return console.log(d);
      });
    });
  });

}).call(this);
